pipeline{
    agent any
    stages{
        stage("Build Frontend"){
            steps{
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/KaZengZhong/Evaluacion1_Tingeso']])
                dir("prestabanco-frontend"){
                    bat "npm install"
                    bat "npm run build"
                }
            }
        }
        stage("Build and Push Docker Image"){
            steps{
                dir("prestabanco-frontend"){
                    script{
                         withDockerRegistry(credentialsId: 'docker-credentials'){
                            bat "docker build -t kahaozeng/prestabanco-frontend ."
                            bat "docker push kahaozeng/prestabanco-frontend"
                        }
                    }                    
                }
            }
        }
    }
}